name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/portfolio:latest .

      - name: Push Image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/portfolio:latest

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: "root"
          VPS_HOST: "ssh.starkbak.net"
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          # SSH to VPS and pull the image from GHCR
          ssh -i private_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            docker pull ghcr.io/${{ github.repository }}/portfolio:latest

            # Stop and remove old container
            docker stop portfolio-app || true
            docker rm portfolio-app || true

            # Run the new container
            docker run -d --name portfolio-app -p 3000:3000 --restart always ghcr.io/${{ github.repository }}/portfolio:latest
          EOF
